### ISSUE TITLE
Doesn't understand -i

### ISSUE THREAD

**Issue by yegor256** [yegor256/bibcop#40]
```
$ bibcop -i --fix a.bib
Cannot open file: -i
```

**Comment by oylenshpeegul** [comment]
It looks like bibcop.pl accepts anything that doesn't start with two dashes as a file name

https://github.com/yegor256/bibcop/blob/master/bibcop.pl#L834

Perhaps change it to one dash?

```perl
my ($file) = grep { not($_ =~ /^-.*$/) } @ARGV;
```

**Comment by yegor256** [comment]
@oylenshpeegul indeed, the fix is simple, but we should also write a unit test for it. If you can make a pull request, I will appreciate!

**Comment by yegor256** [comment]
fixed
