### ISSUE TITLE
Can't recognise the pages in format `p/p`

### ISSUE THREAD

**Issue by maxonfjvipon** [yegor256/bibcop#50]
Here's the reference taken from [here](https://ieeexplore.ieee.org/document/477889):
```
@inproceedings{coombes1995codegen,
  pages={7/1--7/2},
  ...
}
```

Bibcop says: `Package bibcop Warning: The format of the 'pages' is wrong, in the 'coombes1995codegen' bib entry.`

**Comment by yegor256** [comment]
@maxonfjvipon I suggest this:

```
volume=7,
pages={1--2}
```
