### ISSUE TITLE
title warnings

### ISSUE THREAD

**Issue by MikhailLipanin** [yegor256/bibcop#9]
The main question of `bibcop` rules for parsing is: Do we need all titles be the "each-word-capitalized"-style, or we need to use title as it is in original version of a paper?

If the answer is first one, then we need to make more complex rules of capitalizing letters: for example should we make the word after the `"-"` as uppercase? or do we need to make uppercase letters after `":"`, `";"` or `""`?

**Comment by MikhailLipanin** [comment]
@yegor256 WDYT?

**Comment by MikhailLipanin** [comment]
If the paper is published, it has its own `doi`, and usually on its site, there is a possibility to get the `cite` of this paper.
I don't know, can it be done via sending a request to this `doi`-site of each paper and try to get it from there. If not, we can just print the `warning` about titles, but don't change the tittles themselves, since it can violate the original title.

**Comment by yegor256** [comment]
@MikhailLipanin see de8196b it helps?

**Comment by MikhailLipanin** [comment]
@yegor256 yes
